services:
  rails:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s"
    volumes:
      - .:/rails
    environment:
      TZ: Asia/Tokyo
      BINDING: 0.0.0.0
      PGHOST: postgres
      PGUSER: postgres
      PGPASSWORD: postgres
      PORT: 3000
    ports:
      - "3000:3000"

    depends_on:
    - redis
    - postgres

  redis:
    image: redis:7.2
    restart: unless-stopped
    volumes:
    - redis-data:/data

  postgres:
    image: postgres:16.1
    restart: unless-stopped
    networks:
    - default
    volumes:
    - postgres-data:/var/lib/postgresql/data
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres

volumes:
  redis-data:
  postgres-data:
